name: 'Retry command'
description: 'Retries any command with configurable attempts and delay'
inputs:
  command:
    description: 'The command to retry'
    required: true
  max_attempts:
    description: 'Maximum number of retry attempts'
    required: false
    default: '12'
  delay:
    description: 'Delay between attempts in seconds'
    required: false
    default: '30'

runs:
  using: 'composite'
  steps:
    - name: Retry command
      shell: bash
      env:
        INPUT_MAX_ATTEMPTS: ${{ inputs.max_attempts }}
        INPUT_DELAY: ${{ inputs.delay }}
        INPUT_COMMAND: ${{ inputs.command }}
      run: |
        # Generic retry function: configurable attempts and delay
        retry_command() {
          local max_attempts=${INPUT_MAX_ATTEMPTS}
          local delay=${INPUT_DELAY}
          local attempt=1
          local command="${INPUT_COMMAND}"

          while [ $attempt -le $max_attempts ]; do
            echo "Attempt $attempt/$max_attempts: Running command..."
            echo "Command: $command"
            if eval "$command"; then
              echo "Command succeeded on attempt $attempt"
              return 0
            else
              echo "Attempt $attempt failed"
              if [ $attempt -lt $max_attempts ]; then
                echo "Waiting $delay seconds before retry..."
                sleep $delay
              fi
            fi
            attempt=$((attempt + 1))
          done

          echo "Command failed after $max_attempts attempts"
          return 1
        }

        retry_command
