name: Codeowners - Content Strategy

# **What it does**: Automatically add reviewers based on paths, but only for the docs-internal repo.
# **Why we have it**: So we can have reviewers automatically without getting open source notifications.
# **Who does it impact**: Docs team.

on:
  pull_request:
    paths:
      - 'contributing/content-*.md'
      - 'content/contributing/**.md'

jobs:
  codeowners-content-strategy:
    if: ${{ github.repository == 'github/docs-internal' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@b32f140b0c872d58512e0a66172253c302617b90 # v4.0.0

      - name: Add Content Strategy as a reviewer
        env:
          GH_TOKEN: ${{ secrets.DOCS_BOT_PAT_WRITEORG_PROJECT }}
          PR: ${{ github.event.pull_request.html_url }}
        run: |
          has_reviewer=$(
            gh pr view $PR --json reviews |
            jq 'any(.reviews[]; select(length > 0))'
          )
          if ! $has_reviewer
          then
            gh pr edit $PR --add-reviewer github/docs-content-strategy
          fi
