name: Validate asset images

# **What it does**: Run ./src/assets/scripts/validate-asset-images.js on all images in assets/
# **Why we have it**: To protect from innocent and potentially malicious bad image assets
# **Who does it impact**: Docs content.

on:
  workflow_dispatch:
  pull_request:
    paths:
      - 'assets/**'

permissions:
  contents: read

jobs:
  validate-asset-images:
    if: ${{ github.repository == 'github/docs-internal' || github.repository == 'github/docs' }}
    runs-on: ubuntu-latest
    steps:
      - name: Check out repo
        uses: actions/checkout@b32f140b0c872d58512e0a66172253c302617b90 # v4.0.0

      - uses: ./.github/actions/node-npm-setup

      - name: Validate all asset images
        run: src/assets/scripts/validate-asset-images.js
